// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ctrl

import (
	"TechBE/api/ctrl"
)

type ControllerV1 struct{}

func NewV1() ctrl.ICtrlV1 {
	return &ControllerV1{}
}
